services:
  manga-suwayomi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4567"
    volumes:
      - suwayomi-data:/home/suwayomi/.local/share/Tachidesk
    networks:
      - coolify

volumes:
  suwayomi-data:

networks:
  coolify:
    external: true
