services:
  manga-suwayomi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4567"
    volumes:
      - suwayomi-data:/home/suwayomi/.local/share/Tachidesk
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.manga-http.entryPoints=http"
      - "traefik.http.routers.manga-http.middlewares=redirect-to-https"
      - "traefik.http.routers.manga-http.rule=Host(`manga.michel.filipkin.com`) || Host(`manga.stapulasolutions.com`) || Host(`discover.stapulasolutions.com`)"
      - "traefik.http.routers.manga-http.service=manga-svc"
      - "traefik.http.routers.manga-https.entryPoints=https"
      - "traefik.http.routers.manga-https.middlewares=gzip"
      - "traefik.http.routers.manga-https.rule=Host(`manga.michel.filipkin.com`) || Host(`manga.stapulasolutions.com`) || Host(`discover.stapulasolutions.com`)"
      - "traefik.http.routers.manga-https.service=manga-svc"
      - "traefik.http.routers.manga-https.tls=true"
      - "traefik.http.routers.manga-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.manga-svc.loadbalancer.server.port=4567"

volumes:
  suwayomi-data:

networks:
  coolify:
    external: true
